name: hearthbites
description: HearthBites - Home Food Marketplace with Rider Delivery
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.10
  
  # Routing
  go_router: ^13.0.1
  
  # HTTP & API
  dio: ^5.4.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  geolocator: ^11.0.0
  
  # Firebase (for FCM)
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # UI
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/images/
  
  # Fonts (optional)
  # fonts:
  #   - family: Urdu
  #     fonts:
  #       - asset: fonts/NotoNastaliq-Regular.ttf

# Enable generate flag for l10n
flutter:
  generate: true

