// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by running: flutter pub run build_runner build

part of 'user.dart';

// Stub file - will be generated by build_runner
// Run: flutter pub run build_runner build --delete-conflicting-outputs

